# Generated by Django 2.2 on 2019-09-21 19:50

from django.db import migrations, models
import jsonfield.fields
import s3_file_details.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='filerecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=None, storage=s3_file_details.models.OverwriteStorage(), upload_to='')),
                ('filename', models.CharField(default=None, max_length=100, null=True)),
                ('filetype', models.CharField(default=None, max_length=100, null=True)),
                ('filename_Timestamp', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('return_type', models.CharField(default=None, max_length=100, null=True)),
                ('Action_Status', models.CharField(default=None, max_length=100, null=True)),
                ('row_no', models.CharField(default=None, max_length=100, null=True)),
                ('sheet_name', models.CharField(default=None, max_length=100, null=True)),
                ('HQId', models.CharField(default=None, max_length=100, null=True)),
                ('sub_state', models.CharField(default=None, max_length=100, null=True)),
                ('stock_id', models.CharField(default=None, max_length=100, null=True)),
                ('Branch_id', models.CharField(default=None, max_length=100, null=True)),
                ('Timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('Uploaded_by', models.DateTimeField(auto_now_add=True, null=True)),
                ('Uploadedtimestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('Merge_by', models.CharField(default=None, max_length=100, null=True)),
                ('Merge_Batch_Id', models.CharField(default=None, max_length=100, null=True)),
                ('Deleted_by', models.CharField(default=None, max_length=100, null=True)),
                ('Archived_by', models.CharField(default=None, max_length=100, null=True)),
                ('processed_by', models.CharField(default=None, max_length=100, null=True)),
                ('raw_file_path', models.CharField(default=None, max_length=100, null=True)),
                ('processed_file_path', models.CharField(default=None, max_length=100, null=True)),
                ('error_file_path', models.CharField(default=None, max_length=100, null=True)),
                ('control_summary_path', models.CharField(default=None, max_length=100, null=True)),
                ('Merge_file_path', models.CharField(default=None, max_length=100, null=True)),
                ('Company_Id', models.CharField(default=None, max_length=100, null=True)),
                ('type', models.CharField(default=None, max_length=100, null=True)),
                ('financial_year', models.CharField(default=None, max_length=100, null=True)),
                ('month', models.CharField(default=None, max_length=100, null=True)),
                ('file_size', models.CharField(default=None, max_length=100, null=True)),
                ('Merge_Reference', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Template_Name', models.CharField(default=None, max_length=100, null=True)),
                ('column_header', jsonfield.fields.JSONField()),
                ('filename', models.CharField(default=None, max_length=100, null=True)),
                ('row_no', models.CharField(default=None, max_length=100, null=True)),
                ('sheet_name', models.CharField(default=None, max_length=100, null=True)),
                ('Company_Id', models.CharField(default=None, max_length=100, null=True)),
                ('filename_Timestamp', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('Type', models.CharField(default=None, max_length=100, null=True)),
                ('on_off', models.BooleanField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='merge_template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Id', models.CharField(default=None, max_length=100, null=True)),
                ('filename', models.CharField(default=None, max_length=100, null=True)),
                ('filename_timestamp', models.CharField(max_length=100, null=True)),
                ('row_no', models.CharField(default=None, max_length=100, null=True)),
                ('sheet_name', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
    ]
