# Generated by Django 2.2 on 2019-09-22 12:29

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('s3_file_details', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='merge_template',
        ),
        migrations.AlterField(
            model_name='mapping',
            name='column_header',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
