# Generated by Django 2.2 on 2019-10-04 10:41

from django.db import migrations, models
import s3_file_details.models


class Migration(migrations.Migration):

    dependencies = [
        ('s3_file_details', '0002_auto_20190922_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=None, storage=s3_file_details.models.OverwriteStorage(), upload_to='')),
                ('sheet_name', models.CharField(default=None, max_length=100, null=True)),
                ('row_no', models.CharField(default=None, max_length=100, null=True)),
                ('Company_Id', models.CharField(default=None, max_length=100, null=True)),
                ('Type', models.CharField(default=None, max_length=100, null=True)),
                ('file_size', models.CharField(default=None, max_length=100, null=True)),
                ('Uploadedtimestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('Uploaded_by', models.DateTimeField(auto_now_add=True, null=True)),
                ('filename_Timestamp', models.CharField(blank=True, default=None, max_length=150, null=True)),
            ],
        ),
    ]
