# Generated by Django 2.2 on 2019-10-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3_file_details', '0003_master_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='Action_Status',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
