# Generated by Django 2.2 on 2019-10-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3_file_details', '0005_auto_20191007_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerecord',
            name='Deleted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
