# Generated by Django 2.2 on 2019-10-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3_file_details', '0006_filerecord_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerecord',
            name='status',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
