# Generated by Django 2.2 on 2019-10-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3_file_details', '0007_filerecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerecord',
            name='month2',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
