# Generated by Django 2.2 on 2019-10-22 13:47

from django.db import migrations, models
import s3_file_details.models


class Migration(migrations.Migration):

    dependencies = [
        ('s3_file_details', '0008_filerecord_month2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_table',
            name='file',
            field=models.FileField(default=None, storage=s3_file_details.models.OverwriteStorage(), upload_to='Master_Files'),
        ),
    ]
