# Generated by Django 2.2 on 2019-10-22 14:17

from django.db import migrations, models
import s3_file_details.models


class Migration(migrations.Migration):

    dependencies = [
        ('s3_file_details', '0009_auto_20191022_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_table',
            name='file',
            field=models.FileField(default=None, storage=s3_file_details.models.OverwriteStorage(), upload_to='media/Master_Files/'),
        ),
    ]
