# Generated by Django 2.2 on 2019-10-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s3_file_details', '0011_auto_20191022_1418'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Master_table',
            new_name='Mastertable',
        ),
    ]
