# Generated by Django 2.2 on 2019-10-23 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s3_file_details', '0012_auto_20191022_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgComparisionandarithmeticandfuction2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_in', models.CharField(blank=True, db_column='Data_in', max_length=20, null=True)),
                ('new_column', models.CharField(blank=True, db_column='New_column', max_length=50, null=True)),
                ('rule_id', models.IntegerField(blank=True, db_column='Rule_id', null=True)),
                ('column_value', models.CharField(blank=True, db_column='Column_value', max_length=50, null=True)),
                ('header_col1', models.CharField(blank=True, db_column='Header_Col1', max_length=200, null=True)),
                ('oprator1', models.CharField(blank=True, db_column='Oprator1', max_length=50, null=True)),
                ('header_col2', models.CharField(blank=True, db_column='Header_Col2', max_length=200, null=True)),
                ('oprator2', models.CharField(blank=True, db_column='Oprator2', max_length=50, null=True)),
                ('values', models.CharField(blank=True, db_column='Values', max_length=50, null=True)),
                ('connector', models.CharField(blank=True, max_length=50, null=True)),
                ('set_value', models.CharField(blank=True, db_column='Set_value', max_length=50, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, db_column='Company_name', max_length=200, null=True)),
                ('companyid', models.IntegerField(blank=True, db_column='companyId', null=True)),
                ('template_name', models.CharField(blank=True, db_column='Template_Name', max_length=100, null=True)),
                ('master_id', models.CharField(blank=True, db_column='Master_id', max_length=10, null=True)),
                ('ruletype', models.CharField(blank=True, db_column='ruleType', max_length=20, null=True)),
                ('template', models.ForeignKey(blank=True, db_column='Template_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='s3_file_details.Mapping')),
            ],
        ),
    ]
