# Generated by Django 2.2.4 on 2019-11-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3_file_details', '0013_tgcomparisionandarithmeticandfuction2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgcomparisionandarithmeticandfuction2',
            name='type',
            field=models.CharField(blank=True, db_column='Type', max_length=35, null=True),
        ),
    ]
