# Generated by Django 2.2.4 on 2019-11-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3_file_details', '0014_tgcomparisionandarithmeticandfuction2_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertable',
            name='MasterFileColumns',
            field=models.TextField(default='Na'),
        ),
    ]
