# Generated by Django 2.2.4 on 2019-11-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3_file_details', '0017_auto_20191129_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filerecord',
            old_name='Total_Taxable_Vale',
            new_name='Total_Taxable_Value',
        ),
        migrations.AddField(
            model_name='filerecord',
            name='Reason',
            field=models.TextField(default=None),
        ),
    ]
