# Generated by Django 2.2.4 on 2019-11-29 18:00

from django.db import migrations, models
import s3_file_details.models


class Migration(migrations.Migration):

    dependencies = [
        ('s3_file_details', '0018_auto_20191129_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertable',
            name='file',
            field=models.FileField(default=None, storage=s3_file_details.models.OverwriteStorage(), upload_to=''),
        ),
    ]
